In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.9.1


TF Basics
1) Tensors are like numpy array  
2) Tensors are multi-dimensional arrays with uniform data type(referred to as dtype)
3) All tensors are immutable like Python numbers and strings. They cant be updated

In [4]:
r0t = tf.constant(76)
print(r0t)
print(r0t.numpy())
print(r0t.dtype)
print(r0t.ndim)
print(r0t.shape)

tf.Tensor(76, shape=(), dtype=int32)
76
<dtype: 'int32'>
0
()


In [5]:
r1t = tf.constant([1,2,3,4,5,6,7])
print(r1t)
print(r1t.numpy())
print(r1t.dtype)
print(r1t.ndim)
print(r1t.shape)

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
[1 2 3 4 5 6 7]
<dtype: 'int32'>
1
(7,)


In [6]:
r2t = tf.constant([[1,2,3],[4,55,6]])
print(r2t)
print(r2t.numpy())
print(r2t.dtype)
print(r2t.ndim)
print(r2t.shape)

tf.Tensor(
[[ 1  2  3]
 [ 4 55  6]], shape=(2, 3), dtype=int32)
[[ 1  2  3]
 [ 4 55  6]]
<dtype: 'int32'>
2
(2, 3)


In [7]:
r3t = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(r3t)
print(r3t.numpy())
print(r3t.dtype)
print(r3t.ndim)
print(r3t.shape)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<dtype: 'int32'>
3
(2, 2, 3)


#### Tensors are Immutable

In [12]:
w1 = tf.constant([3,4,5,6,7,8])
print(w1.numpy())
print(w1[0].numpy())
w1[0] = 50
print(w1)

[3 4 5 6 7 8]
3


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

#### Tensors Operations

In [ ]:
a1 = tf.constant([[1,2],[3,4]])
a2 = tf.constant([[7,10],[6,20]])
print(a1.numpy())
print(a2.numpy())

[[1 2]
 [3 4]]
[[ 7 10]
 [ 6 20]]


In [ ]:
print(tf.add(a1,a2).numpy())
print(tf.subtract(a2,a1).numpy())
print(tf.multiply(a1,a2).numpy()) # element wise multiplication
print(tf.divide(a2,a1).numpy())

[[ 8 12]
 [ 9 24]]
[[ 6  8]
 [ 3 16]]
[[ 7 20]
 [18 80]]
[[7. 5.]
 [2. 5.]]


In [ ]:
print(a1+a2)
print(a2-a1)
print(a1*a2)
print(a2/a1)

tf.Tensor(
[[ 8 12]
 [ 9 24]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6  8]
 [ 3 16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 7 20]
 [18 80]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[7. 5.]
 [2. 5.]], shape=(2, 2), dtype=float64)


Architecture for Neural Network

In [10]:
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense


# from tensorflow._api.v1.keras import Sequential
# from tensorflow._api.v1.keras.layers import Dense

from tensorflow.python.keras import Sequential
from tensorflow.python.keras.layers import Dense
# sequential is for binding the layers of neurons
#

ANN Model for Regression
1) Activation function used in hidden layer - relu, leakyrelu
2) Activation function used in output layer - linear
3) Optimizer - adam, rmsprop, sgd
4) Loss Function - mse, mae

In [ ]:
# Suppose shape of x(independent feature) = (200,8)
# Rows = 200, Columns = 8

In [ ]:
m1 = Sequential()                                 # Input layer has 8 neurons
m1.add(Dense(32,activation='relu',input_dim=8))   # hidden layer 1 # H1 has 32 neurons
m1.add(Dense(16,activation='relu'))               # H2 has 16 neurons
m1.add(Dense(8,activation='relu'))                # H3 has 8 neurons
m1.add(Dense(1))                                  # Output layer has 1 neuron, activation='linear'

m1.compile(optimizer='adam',loss='mse')

In [ ]:
print(32*8 + 32)   # 32*8 is weights and 32 is Bias
print(16*32 + 16)

288
528


In [ ]:
m1.summary()
# Input = 8, H1=32,H2=16, H3 =8,Output=1
#             Weights     Bias
# dense=>      32*8    +  32    = 288
# dense_1 =>   16*32   +  16    = 528
# dense_2 =>   8*16    +   8    = 136
# dense_3 =>   1*8     +   1    = 9

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 dense_2 (Dense)             (None, 8)                 136       
                                                                 
 dense_3 (Dense)             (None, 1)                 9         
                                                                 
Total params: 961
Trainable params: 961
Non-trainable params: 0
_________________________________________________________________


ANN Model for Binary Classification
1) Activation function used in hidden layer - relu, leakyrelu
2) Activation function used in output layer - sigmoid
3) Optimizer - adam, rmsprop, sgd
4) Loss Function - binary_crossentropy

In [ ]:
m2 = Sequential()                                 # Input layer has 8 neurons
m2.add(Dense(32,activation='relu',input_dim=8))   # H1 has 32 neurons
m2.add(Dense(16,activation='relu'))               # H2 has 16 neurons
m2.add(Dense(8,activation='relu'))                # H3 has 8 neurons
m2.add(Dense(1,activation='sigmoid'))             # Output layer has 1 neuron, activation='linear'

m2.compile(optimizer='adam',loss='binary_crossnetorpy')

In [ ]:
m2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 32)                288       
                                                                 
 dense_5 (Dense)             (None, 16)                528       
                                                                 
 dense_6 (Dense)             (None, 8)                 136       
                                                                 
 dense_7 (Dense)             (None, 1)                 9         
                                                                 
Total params: 961
Trainable params: 961
Non-trainable params: 0
_________________________________________________________________
